repos:
  # Run lint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.9
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  # Run the tests.
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ./.venv/bin/pytest
      language: system
      types: [python]
      pass_filenames: false
      always_run: true